### ISSUE TITLE
Cannot upload file

### ISSUE THREAD

**Issue by thephucit** [ixudra/curl#118]
I try to upload file but this error happend

<img width="643" alt="Screen Shot 2019-12-31 at 14 43 59" src="https://user-images.githubusercontent.com/13312098/71614017-172f5980-2bdc-11ea-806f-50de2e59767e.png">

This is my code
<img width="672" alt="Screen Shot 2019-12-31 at 14 46 03" src="https://user-images.githubusercontent.com/13312098/71614071-4940bb80-2bdc-11ea-8887-7905ee38609b.png">

**Comment by elimentz** [comment]
Are you sure the error isn't in the `$args` variable? Does it work without the file?

**Comment by pratik007kumar** [comment]
not for me also 
 in logfile 
`*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 80 (#0)
* stopped the pause stream!
* Closing connection 0`

and respond obj 
`{#1551
  +"content": ""
  +"status": 0
  +"contentType": null
  +"error": ""
  +"headers": []
}`

**Comment by elimentz** [comment]
I can't help unless you also provide the request information. Please show me the full request with all options, headers and data you are trying to send.

Also, since you're sending the data to 127.0.0.1, I assume you are in control of the server you're sending it to so you should easily be able to add some logging there to see what goes wrong.

**Comment by elimentz** [comment]
Closed due to inactivity
