### ISSUE TITLE
Any plans to support HEAD requests?

### ISSUE THREAD

**Issue by AdrianwithaW** [ixudra/curl#129]
Not sure if this is still maintained, but this is my go-to library for Curl in PHP, great work  👍

Just curious if you have plans to support HEAD requests?

**Comment by elimentz** [comment]
@AdrianwithaW Added support for HEAD requests in v6.22.0, now in available for download. Thanks for the support!

**Comment by AdrianwithaW** [comment]
Amazingly quick turnaround! Functionally it seems to be fine, but if I run it against the same credentials I'm using with the Guzzle client (that I have to use for the HEAD request currently) I'm getting a 302 back from the same API - I see in [this article about HEAD requests](https://beamtic.com/head-request-curl-php), the `CURLOPT_RETURNTRANSFER` flag is required, but don't see that in your source code, is that possibly why?

**Comment by elimentz** [comment]
@AdrianwithaW You can add any cURL option with the `->withOption()` method, as described in the documentation. In your case that would be:

```php
 $response = Curl::to( $url )
    ->withOption('RETURNTRANSFER', true)
    ->head();
```

That said, the `RETURNTRANSFER` option is set to true by default as per the cURL documentation, so that shouldn't be the problem. I think the `FOLLOWLOCATION` is more likely to be the cause here. Try this:

```php
 $response = Curl::to( $url )
    ->withOption('RETURNTRANSFER', true) // Not necessary but never hurts
    ->withOption('FOLLOWLOCATION', true)
    ->head();
```
