### ISSUE TITLE
PLS add some $curlOptions

### ISSUE THREAD

**Issue by DmitryZyuzin** [ixudra/curl#133]
Hi! I really like your package, but in some cases **i need additional $curlOptions**.
**Please add this to protected $curlOptions in Builder:**

```php
     public function get()
     {
          $this->appendDataToURL();

          return $this->withOption('CUSTOMREQUEST', 'GET')->send();
    }
```

It needed when using GET request with json data body. I know that is not in convinience, but some old API use that.
And.. StandWithUkraine!
Thanks!

**Comment by elimentz** [comment]
@DmitryZyuzin Hi, thanks for using the package. There is no need to update the package since you can add that option yourself.

```php
    $response = Curl::to('http://www.foo.com/bar')
        ->withData( $data )
        ->withOption('CUSTOMREQUEST', 'GET')
        ->get();
```

Even though `CUSTOMREQUEST` is no in the `curlOptions` array by default, you can still set it yourself and it will work perfectly. I actually also do it myself, see the `put()` and `patch()` methods, for example.

**Comment by elimentz** [comment]
No problem, have fun and make something beautiful 🇺🇦
