### ISSUE TITLE
Return Null

### ISSUE THREAD

**Issue by gifary** [ixudra/curl#53]
Hello,
Thanks for being awesome library.

```
$response = Curl::to($this->base_url."lokasi")
        ->withHeader('Authorization: Bearer '.$this->access_token)
        ->withHeader('Accept: application/json')
        ->get();
```

That's my code, In local working properly. But when upload to server always return null that's code. 
 When I check on postman working properly with URL, and acces token on server. Do you have any solutions or suggestion for the best solutions?

**Thank you very much**

**Comment by elimentz** [comment]
Hi Muhammad

Your syntax is correct, so that is obviously not the problem. The most obvious possibility is that the access token and/or the url are not set correctly in the code, have you added a log statement to verify if that is actually the case?

Alternatively you can try to use the `->enableDebug()` function to get some additional information on what is going wrong on the server:

```
$response = Curl::to($this->base_url."lokasi")
        ->withHeader('Authorization: Bearer '.$this->access_token)
        ->withHeader('Accept: application/json')
        ->enableDebug('/path/to/dir/logFile.txt')
        ->get();
```

In the file you will find some more (hopefully helpful) information regarding the request.

**Comment by gifary** [comment]
thanks, someting wrong with configuration server.
