### ISSUE TITLE
Builder does not clean up after curl request

### ISSUE THREAD

**Issue by pimlie** [ixudra/curl#84]
The send method does not cleanup request specific parameters after curl has been executed. Because of this, if you do first a post request and then a get request eg the POST data will be used as GET parameters.

Example:
```php
$curl = new Builder;
$curl->to('http://myurl')->withData(['var' => 'test'])->post();
$curl->to('http://myurl')->get();
```
The last get request will be to `http://myurl?var=test` instead of _just_ `http://myurl`. If you are posting a lot of data, the get request can easily fail with status `414 Request URI too long`

**Comment by elimentz** [comment]
This is correct. However, you're not using the package as you're supposed to. You should only ever be accessing the CurlService, which will in turn hand you a builder.

Change your code to this and it will work just fine:

```php
$curlService = new CurlService();
$curlService->to('http://myurl')->withData(['var' => 'test'])->post();
$curlService->to('http://myurl')->get();
```

**Comment by pimlie** [comment]
Ah right, do you have plans to support reusing the curl connection? Or would you accept a PR for that?

Afaik re-using the curl instance should give a great performance increase, see:
- https://stackoverflow.com/questions/18046637/should-i-close-curl-or-not/18046877#18046877
- https://stackoverflow.com/questions/972925/persistent-keepalive-http-with-the-php-curl-library

**Comment by elimentz** [comment]
I don't have any immediate plans to add this. The performance gains are undeniable, but the gains don't seem significant enough to bother with it. I can't imagine anyone sending more than 10 cURL requests, or at least not very often. 

Additionally, I think it would greatly complicate things, since the user would have to do a lot more "management", see the example you mentioned in the initial comment. You have to keep in mind: this is a utility library, it's supposed to make your life easier. I don't think adding these kinds of features would help it.

That said, if you can find a way to make this simple and intuitive to use, I'd be more than happy to merge it in. Dazzle me :-)
