### ISSUE TITLE
undefined method Curl::to()

### ISSUE THREAD

**Issue by brunolavergne** [ixudra/curl#95]
Hi there,

I use this code :
Curl::to($this->path)->get();

I get this error in production (not in local)
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Call to undefined method Ixudra\Curl\Facades\Curl::to()

I use Laravel 5.6
composer.json : "ixudra/curl" : "^6.16",

Thanks.
Have a nice day.

**Comment by elimentz** [comment]
Did you run `composer install` on production? Seems the most logical explanation

**Comment by brunolavergne** [comment]
Yes, all my php dependencies have been installed via the `composer install` command. Everything looks in place but the function is not found.

Otherwise, the php cURL extension is active and working properly on the production server.

**Comment by elimentz** [comment]
This is definitely not an extension problem. I assume you have the `use Curl;` statement at the top of your file?

Out of curiosity, did you check to see if the ixudra/curl directory is in your vendor or not? I don't mean to doubt you but it truly seems the most logical explanation by far that the package just isn't there, especially since it works locally.

**Comment by brunolavergne** [comment]
Sorry, I just saw my mistake ...
my `config / app.php` was not configured with the provider and aliase:

`Ixudra \ Curl \ CurlServiceProvider :: class,`
`'Curl' => Ixudra \ Curl \ Facades \ Curl :: class,`

I called directly `use Ixudra\Curl\Facades\Curl;` in my files.
My local environment, more permissive, did not return any errors.

Thank you very much for your help and your library.

**Comment by elimentz** [comment]
Glad to hear everything is resolved. Enjoy the package!
